/************************************************************************************
* @file     : expirationcontroller.h
* @brief    : Shared expiration controller interface.
* @details  : Controls release and PEEP for every normal breath type.
* @author   :
* @date     : 2026-08-26
* @version  : V1.0.0
* @copyright: Copyright (c) 2050
***********************************************************************************/
#ifndef USER_APP_VENTALGO_EXPIRATIONCONTROLLER_H
#define USER_APP_VENTALGO_EXPIRATIONCONTROLLER_H

#include <stdint.h>

#include "actuatorrequest.h"
#include "breathscheduler.h"

#ifdef __cplusplus
extern "C" {
#endif

#define EXPIRATION_CONTROLLER_SAMPLE_PERIOD_S              0.006F
#define EXPIRATION_CONTROLLER_PEEP_KP                       0.25F
#define EXPIRATION_CONTROLLER_PEEP_KI                       0.05F
#define EXPIRATION_CONTROLLER_PEEP_KD                       0.0F
#define EXPIRATION_CONTROLLER_PEEP_EFFORT_MIN             (-1.0F)
#define EXPIRATION_CONTROLLER_PEEP_EFFORT_MAX               1.0F
#define EXPIRATION_CONTROLLER_BLOWER_CORRECTION_SCALE      80.0F
#define EXPIRATION_CONTROLLER_CAPTURE_BLOWER_SCALE_MIN       0.0F
#define EXPIRATION_CONTROLLER_CAPTURE_BLOWER_SCALE_MAX     200.0F
#define EXPIRATION_CONTROLLER_CAPTURE_BLOWER_SCALE_PEEP_BASE 5.0F
#define EXPIRATION_CONTROLLER_CAPTURE_BLOWER_SCALE_PEEP_GAIN 20.0F
#define EXPIRATION_CONTROLLER_RELEASE_BLOWER_KP              0.015F
#define EXPIRATION_CONTROLLER_RELEASE_BLOWER_KI              0.0F
#define EXPIRATION_CONTROLLER_RELEASE_BLOWER_KD              0.0F
#define EXPIRATION_CONTROLLER_RELEASE_BLOWER_EFFORT_MIN     (-1.0F)
#define EXPIRATION_CONTROLLER_RELEASE_BLOWER_EFFORT_MAX       1.0F
#define EXPIRATION_CONTROLLER_RELEASE_BLOWER_EFFORT_SCALE   800.0F
#define EXPIRATION_CONTROLLER_RELEASE_VALVE_KP                 4.0F
#define EXPIRATION_CONTROLLER_RELEASE_VALVE_BASE_OFFSET       65.0F
#define EXPIRATION_CONTROLLER_RELEASE_VALVE_DUTY_MIN          40.0F
#define EXPIRATION_CONTROLLER_RELEASE_VALVE_MAX_STEP           4.0F
#define EXPIRATION_CONTROLLER_RELEASE_PREDICTION_TIME_S         0.06F
#define EXPIRATION_CONTROLLER_RELEASE_CAPTURE_TOLERANCE_RATIO 0.05F
#define EXPIRATION_CONTROLLER_RELEASE_CAPTURE_STABLE_MS      60U
#define EXPIRATION_CONTROLLER_PEEP_RELIEF_DEADBAND          0.2F
#define EXPIRATION_CONTROLLER_PEEP_RELIEF_GAIN              8.0F
#define EXPIRATION_CONTROLLER_PEEP_RELIEF_MAX_OPENING      20.0F
#define EXPIRATION_CONTROLLER_PEEP_SUPPORT_DEADBAND        0.05F
#define EXPIRATION_CONTROLLER_PEEP_SUPPORT_GAIN            24.0F
#define EXPIRATION_CONTROLLER_PEEP_SUPPORT_MAX_CLOSING     20.0F
#define EXPIRATION_CONTROLLER_PEEP_VALVE_MAX_STEP           4.0F
#define EXPIRATION_CONTROLLER_PEEP_VALVE_BASE_OFFSET        65.0F
#define EXPIRATION_CONTROLLER_PEEP_VALVE_PRESSURE_GAIN       2.0F
#define EXPIRATION_CONTROLLER_EXP_VALVE_OPEN_DUTY           0U
#define EXPIRATION_CONTROLLER_EXP_VALVE_CLOSED_DUTY       100U
#define EXPIRATION_CONTROLLER_RELIEF_CLOSED_DUTY           100U
#define EXPIRATION_CONTROLLER_BLOWER_TARGET_MAX            800U
#define EXPIRATION_CONTROLLER_PRESSURE_SLOPE_INTERVAL_S      0.024F
#define EXPIRATION_CONTROLLER_PRESSURE_HISTORY_COUNT         5U
#define EXPIRATION_CONTROLLER_CAPTURE_RAMP_TIME_MS           60U
#define EXPIRATION_CONTROLLER_CAPTURE_BLOWER_START_DUTY      60.0F
#define EXPIRATION_CONTROLLER_CAPTURE_VALVE_BASE_OFFSET      73.0F
#define EXPIRATION_CONTROLLER_CAPTURE_VALVE_PRESSURE_GAIN     0.4F
#define EXPIRATION_CONTROLLER_CAPTURE_PREDICTION_TIME_S       0.024F
#define EXPIRATION_CONTROLLER_CAPTURE_VALVE_KP                2.5F
#define EXPIRATION_CONTROLLER_CAPTURE_VALVE_MAX_STEP          2.0F
#define EXPIRATION_CONTROLLER_CAPTURE_TOLERANCE_MIN           0.3F
#define EXPIRATION_CONTROLLER_CAPTURE_TOLERANCE_MAX           0.5F
#define EXPIRATION_CONTROLLER_CAPTURE_TOLERANCE_PEEP_BASE     5.0F
#define EXPIRATION_CONTROLLER_CAPTURE_TOLERANCE_PEEP_GAIN     0.02F
#define EXPIRATION_CONTROLLER_CAPTURE_STABLE_SLOPE_MAX        3.0F
#define EXPIRATION_CONTROLLER_CAPTURE_STABLE_SAMPLE_COUNT    10U
#define EXPIRATION_CONTROLLER_BLOWER_MAX_STEP              200.0F
#define EXPIRATION_CONTROLLER_EXP_VALVE_CLOSE_MAX_STEP        8.0F
#define EXPIRATION_CONTROLLER_PEEP_ENTRY_RAMP_TIME_MS      500.0F

typedef enum {
    EXPIRATION_CONTROLLER_IDLE = 0,
    EXPIRATION_CONTROLLER_RELEASE,
    EXPIRATION_CONTROLLER_CAPTURE,
    EXPIRATION_CONTROLLER_PEEP,
} eExpirationControllerState;

/** Initialize the shared release and PEEP controller. */
void expirationControllerInit(void);

/** Produce one expiration actuator request for the active breath plan. */
int8_t expirationControllerProcess(const stBreathPlan *plan,
                                   const stActuatorRequest *previousRequest,
                                   stActuatorRequest *request);

/** Return the current expiration-controller state. */
eExpirationControllerState expirationControllerStateGet(void);

#ifdef __cplusplus
}
#endif

#endif /* USER_APP_VENTALGO_EXPIRATIONCONTROLLER_H */
/**************************End of file********************************/
