//
// Created by 7invensun on 2024/1/29.
//
#ifndef GD32F470_FREERTOS_RGBLCD_H
#define GD32F470_FREERTOS_RGBLCD_H

#include "gd32f4xx.h"
#include "FreeRTOS.h"

#define LCD_WIDTH 800
#define LCD_HEIGHT 480
#define LCD_FB_BYTE_PER_PIXEL 1


#define HORIZONTAL_SYNCHRONOUS_PULSE 1
#define HORIZONTAL_BACK_PORCH 46
#define ACTIVE_WIDTH 800
#define HORIZONTAL_FRONT_PORCH 210

#define VERTICAL_SYNCHRONOUS_PULSE 1
#define VERTICAL_BACK_PORCH 23
#define ACTIVE_HEIGHT 480
#define VERTICAL_FRONT_PORCH 22

extern uint16_t *ltdc_lcd_framebuf;

void RGBLCDInit(void);


#endif //GD32F470_FREERTOS_RGBLCD_H
